> csharp supports only runtime exceptions 

> gettype in csharp is similar to getclass in java. To know the type of instance 

        using System;  
        namespace com.example  
        {                      
            public class Test{
                static void Main(String[] args){
                    try{
                        int a = 10;
                        int b = 0;
                        int result = a/b;
                    }catch(Exception e){
                        Console.WriteLine($"exectption type : {e.GetType()}");
                        Console.WriteLine($"exception message : {e.Message}");
                    }
                }
            }   
        }
        
        output : 
        exectption type : System.DivideByZeroException
        exception message : Attempted to divide by zero.
        
        
        
        
#### handling specific exception 
      
              try{
                  int a = 10;
                  int b = 0;
                  int result = a/b;
              }catch(DivideByZeroException d){
                  Console.WriteLine($"{d.ToString()}");
                  Console.WriteLine("denominator must not be zero");
              }                
              catch(Exception e){
                  Console.WriteLine($"exectption type : {e.GetType()}");
                  Console.WriteLine($"exception message : {e.Message}");
              }
               
               
                System.DivideByZeroException: Attempted to divide by zero.
                at com.example.Test.Main (System.String[] args) [0x00005] in <e9da1ad870e84044b14612cd78436c52>:0
                denominator must not be zero                


#### throw keyword : used to throw/raise exception

            using System;  
            namespace com.example  
            {                      
                public class Test{
                    static void Main(String[] args){
                        Test test = new Test();
                        try{
                            String result = test.division(10,0);
                            Console.WriteLine($"{result}");
                        }catch(DivideByZeroException d){
                            Console.WriteLine($"{d.Message}");
                        }                
                    }
                    public String division(int a, int b){
                        if(b == 0){
                            throw new DivideByZeroException("dont sent zero as denominator");
                        }else{
                            return $"result : {a/b}";
                        }
                    }
                }           
            }           
            
            
            output : dont sent zero as denominator
            
            
#### user define exception : 
          using System;  
          namespace com.example  
          {                      
              public class Test{
                  static void Main(String[] args){
                      BankAccount bankAccount = new BankAccount();
                      try{
                          String result = bankAccount.withDraw(6000);
                          Console.WriteLine($"{result}");
                      }catch(InsufficientMoneyException insufficientMoneyException){
                          Console.WriteLine($"{insufficientMoneyException.Message}");
                      }
                  }
              }    

              class BankAccount{
                  public String withDraw(int amount){
                      int balance = 5000;
                      if(amount > balance){
                          throw new InsufficientMoneyException($"amount must be less than {balance}");
                      }else{
                          balance = balance - amount;
                          return $"transaction successful , the balance is {balance}";
                      }
                  }
              }
              [System.Serializable]
                  public class InsufficientMoneyException : System.Exception
                  {
                      public InsufficientMoneyException() { }
                      public InsufficientMoneyException(string message) : base(message) { }
                      public InsufficientMoneyException(string message, System.Exception inner) : base(message, inner) { }
                      protected InsufficientMoneyException(
                          System.Runtime.Serialization.SerializationInfo info,
                          System.Runtime.Serialization.StreamingContext context) : base(info, context) { }
                  }       
          }             

          output : 
          amount must be less than 5000


